- name: Print Parameter Store
  hosts: localhost
  tasks:
   - name: Print a parameter
     ansible.builtin.debug:
      msg: ="{{ lookup('aws_ssm', 'param.dev.catalogue.MONGO', region='us-east-1' ) }}"