- name: Demo on loops
  hosts: localhost
  tasks:
    - name: Loop on list
      ansible.builtin.debug:
        msg: "Fruit Name - {{item}}"
      loop:
        - Apples
        - Oranges
    - name: Loop on list of maps
      ansible.builtin.debug:
        msg: "Fruit Name - {{item.name}} , Count = {{item.count}}"
      loop:
        - {name: "oranges", count:100}
        - {name: "apples", count:50}