- name: filter
  hosts: localhost
  vars:
    CONTENT: "Fruit - Apple\nDrink - Coke\nFood - Burger"
  tasks:
     - name: filter
       ansible.builtin.debug:
         msg: "{{ CONTENT | split('\n') | regex_findall('Drink.*') }}"

#- name: filter
#  hosts: localhost
#  vars:
#    CONTENT: "Fruit - Apple\nDrink - Coke\nFood - Burger"
#  tasks:
#    - name: filter
#      ansible.builtin.debug:
#        msg: "{{ CONTENT | regex_findall('Drink.*') }}"
